version: '2'

services:
    app:
        image: contacts-app
        build: .
        environment: 
            MONGO_URL: "mongodb://db/contact-list"
        depends_on: 
            - db
        ports: 
            - "3000:3000"

    db:
        image: mongo